"""Table 5 (DEFINE 1.1 manual, Aug 2022) labels for endogenous variables.

Used by generate_define_notebook.py to expand equation descriptions.
Equation numbers stay as a short eqN suffix (manual Eq. (N) -> eqN).
"""

from __future__ import annotations

import re

SECTOR = {
    "1": "mining and utilities",
    "2": "manufacturing and construction",
    "3": "transport",
    "4": "other sectors",
}

# Manual Table 5 descriptions, keyed by notebook/R names.
TABLE5: dict[str, str] = {
    "A": "advances (US$ tn)",
    "A_N": "notional central-bank advances before the no-negative-advances rule (US$ tn)",
    "B": "value of total corporate bonds (US$ tn)",
    "BAILOUT": "bailout funds provided to banks by government (US$ tn)",
    "BAILOUT_CAR": "bailout needed to restore the capital-adequacy floor (US$ tn)",
    "BAILOUT_levB": "bailout needed to restore the bank-leverage ceiling (US$ tn)",
    "B_C": "value of conventional corporate bonds (US$ tn)",
    "b_C": "number of conventional corporate bonds (tn)",
    "B_CCB": "conventional corporate bonds held by central banks (US$ tn)",
    "b_CCB": "number of conventional corporate bonds held by central banks (tn)",
    "B_CH": "conventional corporate bonds held by households (US$ tn)",
    "b_CH": "number of conventional corporate bonds held by households (tn)",
    "B_C_issue": "new conventional bond issues (US$ tn)",
    "B_G": "value of green corporate bonds (US$ tn)",
    "b_G": "number of green corporate bonds (tn)",
    "B_GCB": "green corporate bonds held by central banks (US$ tn)",
    "b_GCB": "number of green corporate bonds held by central banks (tn)",
    "B_GH": "green corporate bonds held by households (US$ tn)",
    "b_GH": "number of green corporate bonds held by households (tn)",
    "B_G_issue": "new green bond issues (US$ tn)",
    "BP": "profits of banks (US$ tn)",
    "BP_D": "distributed profits of banks (US$ tn)",
    "BP_U": "retained profits of banks (US$ tn)",
    "CO_GOV": "government consumption (US$ tn)",
    "CO_PRI": "household consumption (US$ tn)",
    "CO_PRI_N": "notional consumption when no supply-side constraint binds (US$ tn)",
    "CAP": "capital of banks (US$ tn)",
    "CAP_before": "bank capital before the bailout (US$ tn)",
    "CAR": "capital adequacy ratio",
    "CAR_before": "capital adequacy ratio before the bailout",
    "CAR_per": "capital adequacy ratio (%)",
    "CBP": "central-bank profits remitted to government (US$ tn)",
    "CEN": "carbon mass of fossil energy (Gt)",
    "CO2_CUM": "cumulative CO2 emissions (GtCO2)",
    "CO2_ratio": "fossil emissions relative to 2021",
    "CON_E": "fossil energy resources converted into reserves (EJ)",
    "CON_M": "material resources converted into reserves (Gt)",
    "con_change": "consumption-adjustment factor under sufficiency",
    "coupon_C": "fixed coupon paid per conventional corporate bond (US$)",
    "coupon_G": "fixed coupon paid per green corporate bond (US$)",
    "CR": "degree of total credit rationing on loans",
    "CR_C": "degree of credit rationing on conventional loans",
    "CR_G": "degree of credit rationing on green loans",
    "D": "deposits (US$ tn)",
    "D_N": "notional household deposits before buffering (US$ tn)",
    "DC": "stock of durable consumption goods (US$ tn)",
    "def": "firms' rate of default",
    "def_per": "firms' default rate (%)",
    "DEM": "demolished/discarded socio-economic stock (Gt)",
    "dep_E": "energy depletion ratio",
    "dep_M": "matter depletion ratio",
    "Depreciation": "capital consumption (US$ tn)",
    "DL": "amount of defaulted loans (US$ tn)",
    "DP": "distributed profits of firms (US$ tn)",
    "dsr": "debt service ratio of firms",
    "D_T": "total proportional damage caused by climate change",
    "D_TF": "climate damage that hits fund-service resources directly",
    "D_TP": "climate damage that reduces fund-service productivities",
    "E": "energy used for the production of output (EJ)",
    "ED": "dissipated energy (EJ)",
    "EMIS": "total CO2 emissions (GtCO2)",
    "EMIS_F": "fossil CO2 emissions (GtCO2)",
    "EMIS_F_Y": "fossil emissions intensity of output (GtCO2 / US$ tn)",
    "EMIS_L": "land-use CO2 emissions (GtCO2)",
    "endog": "endogenous renewable-cost growth term",
    "E_F": "energy produced from fossil sources (EJ)",
    "E_N_ratio": "energy per employee (EJ / bn people)",
    "E_NF": "energy produced from non-fossil sources (EJ)",
    "E_ratio": "energy use relative to 2021",
    "GNS": "government net saving (US$ tn)",
    "g_bC": "growth rate of conventional bond quantities",
    "g_bG": "growth rate of green bond quantities",
    "gC": "growth rate of private consumption",
    "g_EMIS_L": "growth rate of land-use emissions",
    "g_EN_ratio": "growth rate of energy per employee",
    "gGOVCO": "growth rate of government consumption",
    "g_h": "growth rate of working hours",
    "gI": "growth rate of private investment",
    "g_K": "growth rate of private capital",
    "g_L_per": "growth rate of loans (%)",
    "g_lambda": "growth rate of labour productivity",
    "g_lambda_30": "growth rate of the autonomous green-bond portfolio parameter",
    "g_lf": "growth rate of the labour force",
    "g_omega": "growth rate of CO2 intensity of fossil energy",
    "g_pC": "growth rate of the conventional bond price",
    "g_pG": "growth rate of the green bond price",
    "g_POP": "growth rate of population",
    "g_POP_stag": "stagnation adjustment on population growth",
    "g_star_N": "growth rate of labour-constrained potential output",
    "g_ucn": "growth rate of the pre-tax LCOE of non-renewable energy",
    "g_ucr": "growth rate of the pre-subsidy LCOE of renewable energy",
    "g_x_20": "growth rate of the autonomous green-bond finance share",
    "g_Y": "growth rate of output",
    "g_Y_cum": "cumulative output growth from 2021",
    "g_Y_per": "growth rate of output (%)",
    "g_YE_ratio": "growth rate of output per unit of energy",
    "g_beta_0": "growth rate of the autonomous green-investment share",
    "gov_SUB": "green subsidy rate",
    "greenI": "share of private investment that is green",
    "h": "annual working hours per employee",
    "haz_flow": "hazardous waste generated this year (Gt)",
    "hazratio": "cumulative hazardous waste per person (t/person)",
    "HPM": "high-powered money (US$ tn)",
    "HW_CUM": "cumulative hazardous waste (Gt)",
    "I": "total investment, private plus public (US$ tn)",
    "I_GOV": "investment of the government sector (US$ tn)",
    "I_PRI": "investment of the private sector (US$ tn)",
    "I_PRI^D": "desired total private investment (US$ tn)",
    "IC_GOV": "conventional investment of the government sector (US$ tn)",
    "IC_PRI": "conventional investment of the private sector (US$ tn)",
    "IC_PRI^D": "desired conventional private investment (US$ tn)",
    "IC_cum": "cumulative conventional investment (US$ tn)",
    "IG_GOV": "green investment of the government sector (US$ tn)",
    "IG_PRI": "green investment of the private sector (US$ tn)",
    "IG_PRI^D": "desired green private investment (US$ tn)",
    "IG_cum": "cumulative green investment (US$ tn)",
    "IG_E": "energy-related green investment (US$ tn)",
    "IG_E_Y": "energy-related green investment as a share of output (%)",
    "IG_E_Y_cum": "cumulative energy-related green investment / output",
    "illiq": "firms' illiquidity ratio",
    "Interest": "net interest and coupon payments of firms (US$ tn)",
    "int_C": "interest rate on conventional loans",
    "int_G": "interest rate on green loans",
    "K": "total capital stock (US$ tn)",
    "K_GOV": "capital stock of the government (US$ tn)",
    "K_PRI": "capital stock of firms (US$ tn)",
    "KC": "conventional capital stock (US$ tn)",
    "KC_GOV": "conventional capital stock of government (US$ tn)",
    "KC_PRI": "conventional capital stock of firms (US$ tn)",
    "KCE": "conventional energy capital stock (US$ tn)",
    "KCNE": "conventional non-energy capital stock (US$ tn)",
    "KG": "green capital stock (US$ tn)",
    "KG_GOV": "green capital stock of government (US$ tn)",
    "KG_PRI": "green capital stock of firms (US$ tn)",
    "KGE": "green energy capital stock (US$ tn)",
    "KGNE": "green non-energy capital stock (US$ tn)",
    "KSEQ": "sequestration capital (US$ tn)",
    "KGE_KCE": "green-to-conventional energy capital ratio",
    "KGNE_KCNE": "green-to-conventional non-energy capital ratio",
    "KSEQ_KCE": "sequestration-to-conventional energy capital ratio",
    "L": "total loans of firms (US$ tn)",
    "LC": "conventional loans (US$ tn)",
    "LG": "green loans (US$ tn)",
    "lambda": "hourly labour productivity",
    "lambda_30": "households' autonomous portfolio parameter for green bonds",
    "lambda_40": "households' portfolio parameter responding to climate damage",
    "lambda_perworker": "annual labour productivity per employee",
    "lev_B": "banks' leverage ratio",
    "lev_B_before": "banks' leverage ratio before the bailout",
    "lf": "labour force-to-population ratio",
    "lf_1": "autonomous labour force-to-population ratio",
    "LF": "labour force (bn people)",
    "LG_L_ratio": "share of green loans in total loans",
    "LG_L_ratio_pseudo": "green-loan share using desired new lending",
    "M": "extraction of new matter from the ground, excluding fossil carbon (Gt)",
    "MY": "matter necessary for the production of output (Gt)",
    "mu": "material intensity (Gt / US$ tn)",
    "N": "number of employees (bn people)",
    "NLC^D": "desired new conventional loans after credit rationing (US$ tn)",
    "NLC^DN": "desired new conventional loans before rationing (US$ tn)",
    "NLG^D": "desired new green loans after credit rationing (US$ tn)",
    "NLG^DN": "desired new green loans before rationing (US$ tn)",
    "O2": "oxygen used for the combustion of fossil fuels (Gt)",
    "omega": "CO2 intensity of fossil energy (GtCO2/EJ)",
    "p_C": "market price of conventional corporate bonds (US$)",
    "p_G": "market price of green corporate bonds (US$)",
    "POP": "population (bn)",
    "PORT_BCH": "household portfolio share of conventional bonds",
    "PORT_BGH": "household portfolio share of green bonds",
    "PORT_D": "household portfolio share of deposits",
    "PORT_SECH": "household portfolio share of government securities",
    "r": "rate of total profits",
    "r_total": "firms' profit rate (%)",
    "re": "rate of employment",
    "REC": "recycled socio-economic stock (Gt)",
    "RES_E": "fossil energy resources (EJ)",
    "RES_M": "material resources (Gt)",
    "REV_E": "fossil energy reserves (EJ)",
    "REV_M": "material reserves (Gt)",
    "rho": "recycling rate",
    "RP": "retained profits of firms (US$ tn)",
    "SEC": "total outstanding government securities (US$ tn)",
    "SEC_B": "government securities held by banks (US$ tn)",
    "SEC_BN": "notional bank holdings of government securities (US$ tn)",
    "SEC_CB": "government securities held by central banks (US$ tn)",
    "SEC_CBred": "redundant central-bank securities residual (US$ tn)",
    "SEC_H": "government securities held by households (US$ tn)",
    "seq": "proportion of carbon that is sequestrated",
    "SES": "socio-economic stock (Gt)",
    "sh_L": "share of loans in total firm liabilities",
    "sh_LC": "share of conventional loans in total loans",
    "sh_LG": "share of green loans in total loans",
    "sh_NLG": "share of desired green loans in total desired loans",
    "sh_NLC": "share of desired conventional loans in total desired loans",
    "sigma_0": "autonomous growth rate of labour productivity",
    "sigma_0_optimal": "labour-productivity drift that holds employment on trend",
    "spr": "spread on total loans",
    "spr_C": "spread on conventional loans",
    "spr_G": "spread on green loans",
    "s_W": "wage income share",
    "SUB": "green government subsidies (US$ tn)",
    "t": "calendar index; period 1 is 2021",
    "TAX": "total taxes (US$ tn)",
    "TAX_C": "revenues from carbon taxes (US$ tn)",
    "TAX_F": "taxes on firms' profits (US$ tn)",
    "TAX_H": "taxes on households' disposable income (US$ tn)",
    "tau_C": "carbon tax (US$ tn / GtCO2)",
    "TEMP": "surface temperature change from the pre-industrial period (C)",
    "theta": "share of non-fossil energy in total energy",
    "theta_per": "non-fossil energy share (%)",
    "TP": "total profits of firms (US$ tn)",
    "TP_G": "total gross profits of firms (US$ tn)",
    "tucn": "total unit cost of generating non-renewable energy after carbon tax",
    "tucr": "total unit cost of generating renewable energy after subsidy",
    "u": "rate of capacity utilisation",
    "ucn": "pre-tax levelised cost of generating non-renewable energy (US$ tn/EJ)",
    "ucr": "pre-subsidy levelised cost of generating renewable energy (US$ tn/EJ)",
    "ue": "rate of energy utilisation",
    "um": "rate of matter utilisation",
    "ur": "unemployment rate",
    "ur_per": "unemployment rate (%)",
    "v": "capital productivity",
    "V_CB": "wealth of central banks (US$ tn)",
    "V_H": "wealth of households (US$ tn)",
    "V_HF": "financial wealth of households (US$ tn)",
    "W": "waste (Gt)",
    "wage": "annual wage rate (US$ tn / bn employees)",
    "Wbill": "wage bill (US$ tn)",
    "w_C": "risk weight on conventional loans",
    "w_G": "risk weight on green loans",
    "w_LT": "risk weight on total loans",
    "x_1": "proportion of desired conventional investment funded via bonds",
    "x_2": "proportion of desired green investment funded via bonds",
    "x_20": "autonomous proportion of desired green investment funded via bonds",
    "Y": "output (US$ tn)",
    "Y_N": "notional demand-determined output (US$ tn)",
    "Y_star": "potential output (US$ tn)",
    "Y_star_E": "energy-determined potential output (US$ tn)",
    "Y_star_K": "capital-determined potential output (US$ tn)",
    "Y_star_M": "matter-determined potential output (US$ tn)",
    "Y_star_N": "labour-determined potential output (US$ tn)",
    "Y_star_N_Exp": "expected labour-determined potential output (US$ tn)",
    "Y_H": "disposable income of households (US$ tn)",
    "Y_HD": "household disposable income net of durable depreciation (US$ tn)",
    "Y_HG": "gross disposable income of households (US$ tn)",
    "yield_C": "yield on conventional corporate bonds",
    "yield_G": "yield on green corporate bonds",
    "yield_C_per": "conventional bond yield (%)",
    "yield_G_per": "green bond yield (%)",
    "beta": "aggregate share of desired private investment that is green",
    "beta_0": "autonomous share of desired green investment",
    "beta_S1": "share of desired green investment, mining and utilities",
    "beta_S2": "share of desired green investment, manufacturing and construction",
    "beta_S3": "share of desired green investment, transport",
    "beta_S4": "share of desired green investment, other sectors",
    "beta_0_S1": "autonomous share of desired green investment, mining and utilities",
    "beta_0_S2": "autonomous share of desired green investment, manufacturing and construction",
    "beta_0_S3": "autonomous share of desired green investment, transport",
    "beta_0_S4": "autonomous share of desired green investment, other sectors",
    "delta": "depreciation rate of capital stock",
    "epsilon": "energy intensity (EJ / US$ tn)",
    "kappa": "ratio of green private capital to private investment",
    "omega_ratio": "CO2 intensity relative to 2021",
    "mu_ratio": "material intensity relative to 2021",
    "rho_ratio": "recycling rate relative to 2021",
    "epsilon_ratio": "energy intensity relative to 2021",
    "fiscal_balance": "government fiscal balance as a share of output",
    "fiscal_balance_help": "government net lending including central-bank profits (US$ tn)",
    "fiscal_balance_per": "fiscal balance (% of output)",
    "fiscal_balance_help_per": "government net lending including CBP (% of output)",
    "private_balance": "private-sector net lending (US$ tn)",
    "firms_balance": "firm-sector net lending (US$ tn)",
    "households_balance": "household-sector net lending (US$ tn)",
    "banks_balance": "bank-sector net lending (US$ tn)",
    "private_balance_per": "private-sector net lending (% of output)",
    "firms_balance_per": "firm-sector net lending (% of output)",
    "households_balance_per": "household-sector net lending (% of output)",
    "banks_balance_per": "bank-sector net lending (% of output)",
    "SEC_Y": "government securities-to-output ratio",
    "SEC_Y_per": "government securities-to-output ratio (%)",
    "Y_POP_ratio": "output per capita (US$ tn / bn people)",
    "I_Y_ratio": "private investment-to-output ratio",
    "C_Y_ratio": "private consumption-to-output ratio",
    "C_K_ratio": "private consumption-to-private-capital ratio",
    "Y_K_ratio": "output-to-private-capital ratio",
    "Y_H_Y_ratio": "household disposable income-to-output ratio",
    "Y_H_K_ratio": "household disposable income-to-private-capital ratio",
    "A_K_ratio": "advances-to-private-capital ratio",
    "D_K_ratio": "deposits-to-private-capital ratio",
    "HPM_K_ratio": "high-powered money-to-private-capital ratio",
    "I_K_ratio": "private investment-to-lagged-capital ratio",
    "ID_K_ratio": "desired private investment-to-lagged-capital ratio",
    "L_K": "loans-to-private-capital ratio",
    "W_POP_ratio": "waste per capita (t/person)",
    "Y_E_ratio": "output per unit of energy (US$ tn / EJ)",
    "KG_GOV_Y_ratio": "public green capital-to-output ratio",
    "KC_GOV_Y_ratio": "public conventional capital-to-output ratio",
    "IG_GOV_Y_ratio": "public green investment-to-output ratio",
    "IC_GOV_Y_ratio": "public conventional investment-to-output ratio",
    "KG_Y_ratio": "green capital-to-output ratio",
    "KC_Y_ratio": "conventional capital-to-output ratio",
    "KG_K_ratio": "green capital as a share of total capital",
    "TAX_C_change": "change in carbon-tax revenue (US$ tn)",
    "SUB_change": "change in green subsidies (US$ tn)",
    "IG_GOV_change": "change in public green investment (US$ tn)",
    "KCE_PRI": "conventional energy capital of firms (US$ tn)",
    "KCNE_PRI": "conventional non-energy capital of firms (US$ tn)",
    "KGE_PRI": "green energy capital of firms (US$ tn)",
    "KGNE_PRI": "green non-energy capital of firms (US$ tn)",
    "KSEQ_PRI": "sequestration capital of firms (US$ tn)",
    "IC_PRI^D": "desired conventional private investment (US$ tn)",
    "I_PRI_S": "private investment",
}

_SECTOR_SUFFIX = re.compile(r"^(?P<root>.+)_S(?P<sec>[1-4])$")
_TRAILING_SECTOR_KEYS = (
    "CR_C",
    "IC_PRI^D",
    "IC_PRI",
    "IG_PRI^D",
    "IG_PRI",
    "I_PRI^D",
    "I_PRI",
    "int_C",
    "KC_PRI",
    "KCE_PRI",
    "KCNE_PRI",
    "KG_PRI",
    "KGE_PRI",
    "KGNE_PRI",
    "KSEQ_PRI",
    "LC",
    "LG",
    "NLC^D",
    "NLC^DN",
    "NLG^D",
    "NLG^DN",
    "sh_LC",
    "sh_NLC",
    "spr_C",
    "w_C",
    "beta_0",
    "beta",
)


def table5_label(name: str) -> str:
    if name in TABLE5:
        return TABLE5[name]
    match = _SECTOR_SUFFIX.match(name)
    if match:
        root = match.group("root")
        sector = SECTOR[match.group("sec")]
        base = TABLE5.get(root)
        if base is None and root in _TRAILING_SECTOR_KEYS:
            base = TABLE5.get(root)
        if base is None:
            # beta_S1 is stored as beta_S in TABLE5
            base = TABLE5.get(root + "_S") or TABLE5.get(root)
        if base:
            if base.endswith(sector):
                return base
            return f"{base}, {sector}"
    return ""


def format_equation_desc(name: str, eq_num: str) -> str:
    """Build `table-5 label eqN` (or just the label / eq tag if one side is missing)."""
    label = table5_label(name)
    if eq_num:
        tag = f"eq{eq_num.replace(' ', '')}"
        return f"{label} {tag}" if label else tag
    return label or name
