"""DEFINE 1.1 manual (Aug 2022) labels for endogenous variables and parameters.

Table 5: endogenous variables. Table 6: parameters and exogenous variables.
Used by generate_define_notebook.py for equation and external descriptions.
Equation numbers stay as a short eqN suffix (manual Eq. (N) -> eqN).
"""

from __future__ import annotations

import re

SECTOR = {
    "1": "mining and utilities",
    "2": "manufacturing and construction",
    "3": "transport",
    "4": "other sectors",
}

# Manual Table 5 descriptions, keyed by notebook/R names.
TABLE5: dict[str, str] = {
    "A": "advances (US$ tn)",
    "A_N": "notional central-bank advances before the no-negative-advances rule (US$ tn)",
    "B": "value of total corporate bonds (US$ tn)",
    "BAILOUT": "bailout funds provided to banks by government (US$ tn)",
    "BAILOUT_CAR": "bailout needed to restore the capital-adequacy floor (US$ tn)",
    "BAILOUT_levB": "bailout needed to restore the bank-leverage ceiling (US$ tn)",
    "B_C": "value of conventional corporate bonds (US$ tn)",
    "b_C": "number of conventional corporate bonds (tn)",
    "B_CCB": "conventional corporate bonds held by central banks (US$ tn)",
    "b_CCB": "number of conventional corporate bonds held by central banks (tn)",
    "B_CH": "conventional corporate bonds held by households (US$ tn)",
    "b_CH": "number of conventional corporate bonds held by households (tn)",
    "B_C_issue": "new conventional bond issues (US$ tn)",
    "B_G": "value of green corporate bonds (US$ tn)",
    "b_G": "number of green corporate bonds (tn)",
    "B_GCB": "green corporate bonds held by central banks (US$ tn)",
    "b_GCB": "number of green corporate bonds held by central banks (tn)",
    "B_GH": "green corporate bonds held by households (US$ tn)",
    "b_GH": "number of green corporate bonds held by households (tn)",
    "B_G_issue": "new green bond issues (US$ tn)",
    "BP": "profits of banks (US$ tn)",
    "BP_D": "distributed profits of banks (US$ tn)",
    "BP_U": "retained profits of banks (US$ tn)",
    "CO_GOV": "government consumption (US$ tn)",
    "CO_PRI": "household consumption (US$ tn)",
    "CO_PRI_N": "notional consumption when no supply-side constraint binds (US$ tn)",
    "CAP": "capital of banks (US$ tn)",
    "CAP_before": "bank capital before the bailout (US$ tn)",
    "CAR": "capital adequacy ratio",
    "CAR_before": "capital adequacy ratio before the bailout",
    "CAR_per": "capital adequacy ratio (%)",
    "CBP": "central-bank profits remitted to government (US$ tn)",
    "CEN": "carbon mass of fossil energy (Gt)",
    "CO2_CUM": "cumulative CO2 emissions (GtCO2)",
    "CO2_ratio": "fossil emissions relative to 2021",
    "CON_E": "fossil energy resources converted into reserves (EJ)",
    "CON_M": "material resources converted into reserves (Gt)",
    "con_change": "consumption-adjustment factor under sufficiency",
    "coupon_C": "fixed coupon paid per conventional corporate bond (US$)",
    "coupon_G": "fixed coupon paid per green corporate bond (US$)",
    "CR": "degree of total credit rationing on loans",
    "CR_C": "degree of credit rationing on conventional loans",
    "CR_G": "degree of credit rationing on green loans",
    "D": "deposits (US$ tn)",
    "D_N": "notional household deposits before buffering (US$ tn)",
    "DC": "stock of durable consumption goods (US$ tn)",
    "def": "firms' rate of default",
    "def_per": "firms' default rate (%)",
    "DEM": "demolished/discarded socio-economic stock (Gt)",
    "dep_E": "energy depletion ratio",
    "dep_M": "matter depletion ratio",
    "Depreciation": "capital consumption (US$ tn)",
    "DL": "amount of defaulted loans (US$ tn)",
    "DP": "distributed profits of firms (US$ tn)",
    "dsr": "debt service ratio of firms",
    "D_T": "total proportional damage caused by climate change",
    "D_TF": "climate damage that hits fund-service resources directly",
    "D_TP": "climate damage that reduces fund-service productivities",
    "E": "energy used for the production of output (EJ)",
    "ED": "dissipated energy (EJ)",
    "EMIS": "total CO2 emissions (GtCO2)",
    "EMIS_F": "fossil CO2 emissions (GtCO2)",
    "EMIS_F_Y": "fossil emissions intensity of output (GtCO2 / US$ tn)",
    "EMIS_L": "land-use CO2 emissions (GtCO2)",
    "endog": "endogenous renewable-cost growth term",
    "E_F": "energy produced from fossil sources (EJ)",
    "E_N_ratio": "energy per employee (EJ / bn people)",
    "E_NF": "energy produced from non-fossil sources (EJ)",
    "E_ratio": "energy use relative to 2021",
    "GNS": "government net saving (US$ tn)",
    "g_bC": "growth rate of conventional bond quantities",
    "g_bG": "growth rate of green bond quantities",
    "gC": "growth rate of private consumption",
    "g_EMIS_L": "growth rate of land-use emissions",
    "g_EN_ratio": "growth rate of energy per employee",
    "gGOVCO": "growth rate of government consumption",
    "g_h": "growth rate of working hours",
    "gI": "growth rate of private investment",
    "g_K": "growth rate of private capital",
    "g_L_per": "growth rate of loans (%)",
    "g_lambda": "growth rate of labour productivity",
    "g_lambda_30": "growth rate of the autonomous green-bond portfolio parameter",
    "g_lf": "growth rate of the labour force",
    "g_omega": "growth rate of CO2 intensity of fossil energy",
    "g_pC": "growth rate of the conventional bond price",
    "g_pG": "growth rate of the green bond price",
    "g_POP": "growth rate of population",
    "g_POP_stag": "stagnation adjustment on population growth",
    "g_star_N": "growth rate of labour-constrained potential output",
    "g_ucn": "growth rate of the pre-tax LCOE of non-renewable energy",
    "g_ucr": "growth rate of the pre-subsidy LCOE of renewable energy",
    "g_x_20": "growth rate of the autonomous green-bond finance share",
    "g_Y": "growth rate of output",
    "g_Y_cum": "cumulative output growth from 2021",
    "g_Y_per": "growth rate of output (%)",
    "g_YE_ratio": "growth rate of output per unit of energy",
    "g_beta_0": "growth rate of the autonomous green-investment share",
    "gov_SUB": "green subsidy rate",
    "greenI": "share of private investment that is green",
    "h": "annual working hours per employee",
    "haz_flow": "hazardous waste generated this year (Gt)",
    "hazratio": "cumulative hazardous waste per person (t/person)",
    "HPM": "high-powered money (US$ tn)",
    "HW_CUM": "cumulative hazardous waste (Gt)",
    "I": "total investment, private plus public (US$ tn)",
    "I_GOV": "investment of the government sector (US$ tn)",
    "I_PRI": "investment of the private sector (US$ tn)",
    "I_PRI^D": "desired total private investment (US$ tn)",
    "IC_GOV": "conventional investment of the government sector (US$ tn)",
    "IC_PRI": "conventional investment of the private sector (US$ tn)",
    "IC_PRI^D": "desired conventional private investment (US$ tn)",
    "IC_cum": "cumulative conventional investment (US$ tn)",
    "IG_GOV": "green investment of the government sector (US$ tn)",
    "IG_PRI": "green investment of the private sector (US$ tn)",
    "IG_PRI^D": "desired green private investment (US$ tn)",
    "IG_cum": "cumulative green investment (US$ tn)",
    "IG_E": "energy-related green investment (US$ tn)",
    "IG_E_Y": "energy-related green investment as a share of output (%)",
    "IG_E_Y_cum": "cumulative energy-related green investment / output",
    "illiq": "firms' illiquidity ratio",
    "Interest": "net interest and coupon payments of firms (US$ tn)",
    "int_C": "interest rate on conventional loans",
    "int_G": "interest rate on green loans",
    "K": "total capital stock (US$ tn)",
    "K_GOV": "capital stock of the government (US$ tn)",
    "K_PRI": "capital stock of firms (US$ tn)",
    "KC": "conventional capital stock (US$ tn)",
    "KC_GOV": "conventional capital stock of government (US$ tn)",
    "KC_PRI": "conventional capital stock of firms (US$ tn)",
    "KCE": "conventional energy capital stock (US$ tn)",
    "KCNE": "conventional non-energy capital stock (US$ tn)",
    "KG": "green capital stock (US$ tn)",
    "KG_GOV": "green capital stock of government (US$ tn)",
    "KG_PRI": "green capital stock of firms (US$ tn)",
    "KGE": "green energy capital stock (US$ tn)",
    "KGNE": "green non-energy capital stock (US$ tn)",
    "KSEQ": "sequestration capital (US$ tn)",
    "KGE_KCE": "green-to-conventional energy capital ratio",
    "KGNE_KCNE": "green-to-conventional non-energy capital ratio",
    "KSEQ_KCE": "sequestration-to-conventional energy capital ratio",
    "L": "total loans of firms (US$ tn)",
    "LC": "conventional loans (US$ tn)",
    "LG": "green loans (US$ tn)",
    "lambda": "hourly labour productivity",
    "lambda_30": "households' autonomous portfolio parameter for green bonds",
    "lambda_40": "households' portfolio parameter responding to climate damage",
    "lambda_perworker": "annual labour productivity per employee",
    "lev_B": "banks' leverage ratio",
    "lev_B_before": "banks' leverage ratio before the bailout",
    "lf": "labour force-to-population ratio",
    "lf_1": "autonomous labour force-to-population ratio",
    "LF": "labour force (bn people)",
    "LG_L_ratio": "share of green loans in total loans",
    "LG_L_ratio_pseudo": "green-loan share using desired new lending",
    "M": "extraction of new matter from the ground, excluding fossil carbon (Gt)",
    "MY": "matter necessary for the production of output (Gt)",
    "mu": "material intensity (Gt / US$ tn)",
    "N": "number of employees (bn people)",
    "NLC^D": "desired new conventional loans after credit rationing (US$ tn)",
    "NLC^DN": "desired new conventional loans before rationing (US$ tn)",
    "NLG^D": "desired new green loans after credit rationing (US$ tn)",
    "NLG^DN": "desired new green loans before rationing (US$ tn)",
    "O2": "oxygen used for the combustion of fossil fuels (Gt)",
    "omega": "CO2 intensity of fossil energy (GtCO2/EJ)",
    "p_C": "market price of conventional corporate bonds (US$)",
    "p_G": "market price of green corporate bonds (US$)",
    "POP": "population (bn)",
    "PORT_BCH": "household portfolio share of conventional bonds",
    "PORT_BGH": "household portfolio share of green bonds",
    "PORT_D": "household portfolio share of deposits",
    "PORT_SECH": "household portfolio share of government securities",
    "r": "rate of total profits",
    "r_total": "firms' profit rate (%)",
    "re": "rate of employment",
    "REC": "recycled socio-economic stock (Gt)",
    "RES_E": "fossil energy resources (EJ)",
    "RES_M": "material resources (Gt)",
    "REV_E": "fossil energy reserves (EJ)",
    "REV_M": "material reserves (Gt)",
    "rho": "recycling rate",
    "RP": "retained profits of firms (US$ tn)",
    "SEC": "total outstanding government securities (US$ tn)",
    "SEC_B": "government securities held by banks (US$ tn)",
    "SEC_BN": "notional bank holdings of government securities (US$ tn)",
    "SEC_CB": "government securities held by central banks (US$ tn)",
    "SEC_CBred": "redundant central-bank securities residual (US$ tn)",
    "SEC_H": "government securities held by households (US$ tn)",
    "seq": "proportion of carbon that is sequestrated",
    "SES": "socio-economic stock (Gt)",
    "sh_L": "share of loans in total firm liabilities",
    "sh_LC": "share of conventional loans in total loans",
    "sh_LG": "share of green loans in total loans",
    "sh_NLG": "share of desired green loans in total desired loans",
    "sh_NLC": "share of desired conventional loans in total desired loans",
    "sigma_0": "autonomous growth rate of labour productivity",
    "sigma_0_optimal": "labour-productivity drift that holds employment on trend",
    "spr": "spread on total loans",
    "spr_C": "spread on conventional loans",
    "spr_G": "spread on green loans",
    "s_W": "wage income share",
    "SUB": "green government subsidies (US$ tn)",
    "t": "calendar index; period 1 is 2021",
    "TAX": "total taxes (US$ tn)",
    "TAX_C": "revenues from carbon taxes (US$ tn)",
    "TAX_F": "taxes on firms' profits (US$ tn)",
    "TAX_H": "taxes on households' disposable income (US$ tn)",
    "tau_C": "carbon tax (US$ tn / GtCO2)",
    "TEMP": "surface temperature change from the pre-industrial period (C)",
    "theta": "share of non-fossil energy in total energy",
    "theta_per": "non-fossil energy share (%)",
    "TP": "total profits of firms (US$ tn)",
    "TP_G": "total gross profits of firms (US$ tn)",
    "tucn": "total unit cost of generating non-renewable energy after carbon tax",
    "tucr": "total unit cost of generating renewable energy after subsidy",
    "u": "rate of capacity utilisation",
    "ucn": "pre-tax levelised cost of generating non-renewable energy (US$ tn/EJ)",
    "ucr": "pre-subsidy levelised cost of generating renewable energy (US$ tn/EJ)",
    "ue": "rate of energy utilisation",
    "um": "rate of matter utilisation",
    "ur": "unemployment rate",
    "ur_per": "unemployment rate (%)",
    "v": "capital productivity",
    "V_CB": "wealth of central banks (US$ tn)",
    "V_H": "wealth of households (US$ tn)",
    "V_HF": "financial wealth of households (US$ tn)",
    "W": "waste (Gt)",
    "wage": "annual wage rate (US$ tn / bn employees)",
    "Wbill": "wage bill (US$ tn)",
    "w_C": "risk weight on conventional loans",
    "w_G": "risk weight on green loans",
    "w_LT": "risk weight on total loans",
    "x_1": "proportion of desired conventional investment funded via bonds",
    "x_2": "proportion of desired green investment funded via bonds",
    "x_20": "autonomous proportion of desired green investment funded via bonds",
    "Y": "output (US$ tn)",
    "Y_N": "notional demand-determined output (US$ tn)",
    "Y_star": "potential output (US$ tn)",
    "Y_star_E": "energy-determined potential output (US$ tn)",
    "Y_star_K": "capital-determined potential output (US$ tn)",
    "Y_star_M": "matter-determined potential output (US$ tn)",
    "Y_star_N": "labour-determined potential output (US$ tn)",
    "Y_star_N_Exp": "expected labour-determined potential output (US$ tn)",
    "Y_H": "disposable income of households (US$ tn)",
    "Y_HD": "household disposable income net of durable depreciation (US$ tn)",
    "Y_HG": "gross disposable income of households (US$ tn)",
    "yield_C": "yield on conventional corporate bonds",
    "yield_G": "yield on green corporate bonds",
    "yield_C_per": "conventional bond yield (%)",
    "yield_G_per": "green bond yield (%)",
    "beta": "aggregate share of desired private investment that is green",
    "beta_0": "autonomous share of desired green investment",
    "beta_S1": "share of desired green investment, mining and utilities",
    "beta_S2": "share of desired green investment, manufacturing and construction",
    "beta_S3": "share of desired green investment, transport",
    "beta_S4": "share of desired green investment, other sectors",
    "beta_0_S1": "autonomous share of desired green investment, mining and utilities",
    "beta_0_S2": "autonomous share of desired green investment, manufacturing and construction",
    "beta_0_S3": "autonomous share of desired green investment, transport",
    "beta_0_S4": "autonomous share of desired green investment, other sectors",
    "delta": "depreciation rate of capital stock",
    "epsilon": "energy intensity (EJ / US$ tn)",
    "kappa": "ratio of green private capital to private investment",
    "omega_ratio": "CO2 intensity relative to 2021",
    "mu_ratio": "material intensity relative to 2021",
    "rho_ratio": "recycling rate relative to 2021",
    "epsilon_ratio": "energy intensity relative to 2021",
    "fiscal_balance": "government fiscal balance as a share of output",
    "fiscal_balance_help": "government net lending including central-bank profits (US$ tn)",
    "fiscal_balance_per": "fiscal balance (% of output)",
    "fiscal_balance_help_per": "government net lending including CBP (% of output)",
    "private_balance": "private-sector net lending (US$ tn)",
    "firms_balance": "firm-sector net lending (US$ tn)",
    "households_balance": "household-sector net lending (US$ tn)",
    "banks_balance": "bank-sector net lending (US$ tn)",
    "private_balance_per": "private-sector net lending (% of output)",
    "firms_balance_per": "firm-sector net lending (% of output)",
    "households_balance_per": "household-sector net lending (% of output)",
    "banks_balance_per": "bank-sector net lending (% of output)",
    "SEC_Y": "government securities-to-output ratio",
    "SEC_Y_per": "government securities-to-output ratio (%)",
    "Y_POP_ratio": "output per capita (US$ tn / bn people)",
    "I_Y_ratio": "private investment-to-output ratio",
    "C_Y_ratio": "private consumption-to-output ratio",
    "C_K_ratio": "private consumption-to-private-capital ratio",
    "Y_K_ratio": "output-to-private-capital ratio",
    "Y_H_Y_ratio": "household disposable income-to-output ratio",
    "Y_H_K_ratio": "household disposable income-to-private-capital ratio",
    "A_K_ratio": "advances-to-private-capital ratio",
    "D_K_ratio": "deposits-to-private-capital ratio",
    "HPM_K_ratio": "high-powered money-to-private-capital ratio",
    "I_K_ratio": "private investment-to-lagged-capital ratio",
    "ID_K_ratio": "desired private investment-to-lagged-capital ratio",
    "L_K": "loans-to-private-capital ratio",
    "W_POP_ratio": "waste per capita (t/person)",
    "Y_E_ratio": "output per unit of energy (US$ tn / EJ)",
    "KG_GOV_Y_ratio": "public green capital-to-output ratio",
    "KC_GOV_Y_ratio": "public conventional capital-to-output ratio",
    "IG_GOV_Y_ratio": "public green investment-to-output ratio",
    "IC_GOV_Y_ratio": "public conventional investment-to-output ratio",
    "KG_Y_ratio": "green capital-to-output ratio",
    "KC_Y_ratio": "conventional capital-to-output ratio",
    "KG_K_ratio": "green capital as a share of total capital",
    "TAX_C_change": "change in carbon-tax revenue (US$ tn)",
    "SUB_change": "change in green subsidies (US$ tn)",
    "IG_GOV_change": "change in public green investment (US$ tn)",
    "KCE_PRI": "conventional energy capital of firms (US$ tn)",
    "KCNE_PRI": "conventional non-energy capital of firms (US$ tn)",
    "KGE_PRI": "green energy capital of firms (US$ tn)",
    "KGNE_PRI": "green non-energy capital of firms (US$ tn)",
    "KSEQ_PRI": "sequestration capital of firms (US$ tn)",
    "IC_PRI^D": "desired conventional private investment (US$ tn)",
    "I_PRI_S": "private investment",
}

_SECTOR_SUFFIX = re.compile(r"^(?P<root>.+)_S(?P<sec>[1-4])$")
_TRAILING_SECTOR_KEYS = (
    "CR_C",
    "IC_PRI^D",
    "IC_PRI",
    "IG_PRI^D",
    "IG_PRI",
    "I_PRI^D",
    "I_PRI",
    "int_C",
    "KC_PRI",
    "KCE_PRI",
    "KCNE_PRI",
    "KG_PRI",
    "KGE_PRI",
    "KGNE_PRI",
    "KSEQ_PRI",
    "LC",
    "LG",
    "NLC^D",
    "NLC^DN",
    "NLG^D",
    "NLG^DN",
    "sh_LC",
    "sh_NLC",
    "spr_C",
    "w_C",
    "beta_0",
    "beta",
)


def table5_label(name: str) -> str:
    if name in TABLE5:
        return TABLE5[name]
    match = _SECTOR_SUFFIX.match(name)
    if match:
        root = match.group("root")
        sector = SECTOR[match.group("sec")]
        base = TABLE5.get(root)
        if base is None and root in _TRAILING_SECTOR_KEYS:
            base = TABLE5.get(root)
        if base is None:
            # beta_S1 is stored as beta_S in TABLE5
            base = TABLE5.get(root + "_S") or TABLE5.get(root)
        if base:
            if base.endswith(sector):
                return base
            return f"{base}, {sector}"
    return ""


def format_equation_desc(name: str, eq_num: str) -> str:
    """Build `table-5 label eqN` (or just the label / eq tag if one side is missing)."""
    label = table5_label(name)
    if eq_num:
        tag = f"eq{eq_num.replace(' ', '')}"
        return f"{label} {tag}" if label else tag
    return label or name


# Manual Table 6 (parameters and exogenous variables), keyed by notebook/R names.
# Notebook-only calibration switches and series paths are included at the end.
TABLE6: dict[str, str] = {
    "ad_K": "fraction of gross damages to capital stock avoided through adaptation",
    "ad_LF": "fraction of gross damages to labour force avoided through adaptation",
    "ad_P": "fraction of gross damages to productivity avoided through adaptation",
    "c_1": "propensity to consume out of disposable income",
    "c_2": "propensity to consume out of financial wealth",
    "CAR_min": "minimum capital adequacy ratio",
    "con_E": "conversion rate of fossil energy resources into reserves",
    "con_M": "conversion rate of material resources into reserves",
    "CR_max": "maximum degree of credit rationing",
    "dd_S1": "degree of dirtiness, mining and utilities",
    "dd_S2": "degree of dirtiness, manufacturing and construction",
    "dd_S3": "degree of dirtiness, transport",
    "dd_S4": "degree of dirtiness, other sectors",
    "def_max": "maximum default rate of loans",
    "def_0": "parameter of the default-rate function",
    "def_1": "parameter of the default-rate function",
    "def_2": "sensitivity of the default rate to firms' illiquidity ratio",
    "f_nc": "non-CO2 fraction of total anthropogenic forcing",
    "gov_C": "share of government consumption in output",
    "gov_IC": "share of conventional public investment in output",
    "gov_IG": "share of green public investment in output",
    "h_1": "banks' reserve ratio",
    "h_2": "banks' government securities-to-deposits ratio",
    "haz": "proportion of hazardous waste in total waste",
    "int_A": "interest rate on advances",
    "int_D": "interest rate on deposits",
    "int_S": "interest rate on government securities",
    "l_1": "sensitivity of green/conventional credit rationing to the loan-weight gap",
    "lev_B_max": "maximum bank leverage ratio",
    "lf_2": "sensitivity of the labour force-to-population ratio to hazardous waste",
    "p": "share of productivity damage in total climate damage",
    "p_C_bar": "par value of conventional corporate bonds (US$)",
    "p_G_bar": "par value of green corporate bonds (US$)",
    "pr": "ratio of demand-determined to supply-determined output when a supply constraint binds",
    "r_0": "parameter in the credit-rationing function on total loans",
    "r_1": "parameter in the credit-rationing function on total loans",
    "r_2": "sensitivity of credit rationing to the debt-service ratio",
    "r_3": "sensitivity of credit rationing to the bank capital-adequacy ratio",
    "rep": "loan repayment ratio",
    "s_B": "banks' retention rate",
    "s_C": "share of conventional corporate bonds held by central banks",
    "s_F": "firms' retention rate",
    "s_G": "share of green corporate bonds held by central banks",
    "s_W_0": "parameter in the wage-share function",
    "s_W_1": "sensitivity of the wage share to the unemployment rate",
    "sh_EMIS_F_S1": "share of industrial emissions, mining and utilities",
    "sh_EMIS_F_S2": "share of industrial emissions, manufacturing and construction",
    "sh_EMIS_F_S3": "share of industrial emissions, transport",
    "sh_EMIS_F_S4": "share of industrial emissions, other sectors",
    "sh_GREEN_S1": "share of green investment, mining and utilities",
    "sh_GREEN_S2": "share of green investment, manufacturing and construction",
    "sh_GREEN_S3": "share of green investment, transport",
    "sh_GREEN_S4": "share of green investment, other sectors",
    "sh_GVA_S1": "share of gross value added, mining and utilities",
    "sh_GVA_S2": "share of gross value added, manufacturing and construction",
    "sh_GVA_S3": "share of gross value added, transport",
    "sh_GVA_S4": "share of gross value added, other sectors",
    "spr_0": "parameter in the loan-spread function",
    "spr_1": "sensitivity of the loan spread to the bank capital-adequacy ratio",
    "spr_2": "sensitivity of the loan spread to firms' debt-service ratio",
    "spr_3": "sensitivity of the green/conventional loan spread to the loan-weight gap",
    "TCRE": "transient climate response to cumulative CO2 emissions (C / GtCO2)",
    "ur_T": "target unemployment rate when working hours can change",
    "w_H": "risk weight on high-powered money",
    "w_S": "risk weight on government securities",
    "x_10": "autonomous share of desired conventional investment funded by bonds",
    "x_11": "sensitivity of conventional bond finance to the conventional bond yield",
    "x_21": "sensitivity of green bond finance to the green bond yield",
    "alpha_00": "parameter in the desired-investment function",
    "alpha_01": "parameter in the desired-investment function",
    "alpha_1": "sensitivity of desired investment to capacity utilisation",
    "alpha_2": "sensitivity of desired investment to the profit rate",
    "alpha_31": "sensitivity of desired investment to the unemployment rate",
    "alpha_32": "sensitivity of desired investment to the unemployment rate",
    "alpha_41": "sensitivity of desired investment to the energy-utilisation rate",
    "alpha_42": "sensitivity of desired investment to the energy-utilisation rate",
    "alpha_51": "sensitivity of desired investment to the matter-utilisation rate",
    "alpha_52": "sensitivity of desired investment to the matter-utilisation rate",
    "beta_1": "sensitivity of the desired green-investment share to relative energy costs",
    "beta_2": "sensitivity of the desired green-investment share to the green/conventional funding-cost gap",
    "gamma_E": "share of energy capital in total government capital",
    "gamma_E1": "share of energy capital in total capital, mining and utilities",
    "gamma_E2": "share of energy capital in total capital, manufacturing and construction",
    "gamma_E3": "share of energy capital in total capital, transport",
    "gamma_E4": "share of energy capital in total capital, other sectors",
    "gamma_SEQ1": "share of sequestration capital in green energy capital, mining and utilities",
    "gamma_SEQ2": "share of sequestration capital in green energy capital, manufacturing and construction",
    "delta_0": "depreciation rate of capital when there are no climate damages",
    "epsilon_max": "maximum potential energy intensity (EJ / US$ tn)",
    "epsilon_min": "minimum potential energy intensity (EJ / US$ tn)",
    "zeta_1": "rate of decline of the growth rate of CO2 intensity of fossil energy",
    "zeta_2": "rate of decline of the growth rate of the autonomous green-investment share",
    "zeta_3": "rate of decline of the autonomous growth rate of labour productivity",
    "zeta_4": "rate of decline of the growth rate of the green-bond demand parameter",
    "zeta_5": "rate of decline of the population growth rate",
    "zeta_6": "rate of decline of the autonomous labour force-to-population ratio",
    "zeta_7": "rate of decline of the growth rate of renewable energy cost",
    "zeta_8": "rate of decline of the growth rate of non-renewable energy cost",
    "zeta_9": "rate of decline of the growth rate of land-use emissions",
    "zeta_10": "parameter linking the demand for green bonds to their supply",
    "eta_1": "parameter of the climate-damage function",
    "eta_2": "parameter of the climate-damage function",
    "eta_3": "parameter of the climate-damage function",
    "lambda_10": "parameter of households' portfolio choice (government securities)",
    "lambda_10prime": "response of household securities demand to climate damage",
    "lambda_11": "parameter of households' portfolio choice (government securities)",
    "lambda_12": "parameter of households' portfolio choice (government securities)",
    "lambda_13": "parameter of households' portfolio choice (government securities)",
    "lambda_14": "parameter of households' portfolio choice (government securities)",
    "lambda_15": "parameter of households' portfolio choice (government securities)",
    "lambda_20": "parameter of households' portfolio choice (conventional bonds)",
    "lambda_20prime": "response of household conventional-bond demand to climate damage",
    "lambda_21": "parameter of households' portfolio choice (conventional bonds)",
    "lambda_22": "parameter of households' portfolio choice (conventional bonds)",
    "lambda_23": "parameter of households' portfolio choice (conventional bonds)",
    "lambda_24": "parameter of households' portfolio choice (conventional bonds)",
    "lambda_25": "parameter of households' portfolio choice (conventional bonds)",
    "lambda_30prime": "response of household green-bond demand to climate damage",
    "lambda_31": "parameter of households' portfolio choice (green bonds)",
    "lambda_32": "parameter of households' portfolio choice (green bonds)",
    "lambda_33": "parameter of households' portfolio choice (green bonds)",
    "lambda_34": "parameter of households' portfolio choice (green bonds)",
    "lambda_35": "parameter of households' portfolio choice (green bonds)",
    "lambda_40prime": "response of household deposit demand to climate damage",
    "lambda_41": "parameter of households' portfolio choice (deposits)",
    "lambda_42": "parameter of households' portfolio choice (deposits)",
    "lambda_43": "parameter of households' portfolio choice (deposits)",
    "lambda_44": "parameter of households' portfolio choice (deposits)",
    "lambda_45": "parameter of households' portfolio choice (deposits)",
    "mu_max": "maximum potential material intensity (Gt / US$ tn)",
    "mu_min": "minimum potential material intensity (Gt / US$ tn)",
    "xi": "proportion of durable consumption goods discarded every year",
    "pi_1": "parameter linking the green/conventional non-energy capital ratio to material intensity",
    "pi_2": "parameter linking the green/conventional non-energy capital ratio to material intensity",
    "pi_3": "parameter linking the green/conventional non-energy capital ratio to the recycling rate",
    "pi_4": "parameter linking the green/conventional non-energy capital ratio to the recycling rate",
    "pi_5": "parameter linking the green/conventional energy capital ratio to energy intensity",
    "pi_6": "parameter linking the green/conventional energy capital ratio to energy intensity",
    "pi_7": "parameter linking the green/conventional energy capital ratio to the non-fossil energy share",
    "pi_8": "parameter linking the green/conventional energy capital ratio to the non-fossil energy share",
    "pi_9": "parameter linking the sequestration/conventional energy capital ratio to the sequestration rate",
    "pi_10": "parameter linking the sequestration/conventional energy capital ratio to the sequestration rate",
    "rho_max": "maximum potential recycling rate",
    "sigma_1": "autonomous growth rate of labour productivity",
    "sigma_2": "sensitivity of labour-productivity growth to output growth",
    "tau_F": "firms' tax rate",
    "tau_H": "households' tax rate",
    "phi": "responsiveness of working hours to the unemployment rate",
    # Notebook calibration / scenario extras (not listed as independent Table 6 rows).
    "car": "conversion factor from CO2 emissions to carbon mass",
    "g_baseline": "baseline growth rate used in the 2021 calibration",
    "duration": "number of dynamic periods after the 2021 snapshot",
    "delta_init": "2021 depreciation rate of capital",
    "epsilon_init": "2021 energy intensity (EJ / US$ tn)",
    "mu_init": "2021 material intensity (Gt / US$ tn)",
    "omega_init": "2021 CO2 intensity of fossil energy (GtCO2/EJ)",
    "rho_init": "2021 recycling rate",
    "ucr_init": "2021 unit cost of renewable energy",
    "E_init": "2021 energy used in production (EJ)",
    "EMIS_F_init": "2021 fossil CO2 emissions (GtCO2)",
    "EMIS_F_3": "2023 fossil CO2 emissions used by carbon-tax rules (GtCO2)",
    "EMIS_F_Y_SSP360": "SSP3-6.0 fossil-emissions intensity path (GtCO2 / US$ tn)",
    "POP_init": "2021 population (bn)",
    "gov_SUB_3": "2023 green subsidy rate",
    "con_change_end": "long-run consumption-adjustment factor under sufficiency",
    "tau_C_4": "2024 carbon tax (US$ tn / GtCO2)",
    "tau_C_baseline": "baseline SSP3 carbon-tax path (US$ tn / GtCO2)",
    "tau_C_baseline_per": "baseline SSP3 carbon-tax path (US$ / tCO2)",
    "tau_C_policy_Medium": "medium carbon-tax policy path (US$ tn / GtCO2)",
    "tau_C_policy_Medium_per": "medium carbon-tax policy path (US$ / tCO2)",
    "tau_C_policy_High": "high carbon-tax policy path (US$ tn / GtCO2)",
    "tau_C_policy_High_per": "high carbon-tax policy path (US$ / tCO2)",
    "tau_C_dummy_M": "switch: apply the medium carbon-tax path",
    "tau_C_dummy_H": "switch: apply the high carbon-tax path",
    "damage_dummy": "switch: include climate damages",
    "random_dummy": "switch: add a random shock to desired investment",
    "random1": "random draw for the desired-investment shock",
    "random2": "random draw for the damage-function shock",
    "cr_rationing_dummy": "switch: include credit rationing in the 2021 investment calibration",
    "dummy_con_change": "switch: apply the sufficiency consumption adjustment",
    "stop_recycling_dummy": "switch: stop recycling",
    "subsidy_increase_dummy": "switch: raise the green subsidy rate",
    "subsidy_ratio": "multiplier on the green subsidy rate when the subsidy switch is on",
    "ucr_dummy": "switch: let renewable energy costs fall endogenously",
    "beta_dummy_0": "switch: raise the autonomous green-investment share from 2026",
    "beta_is_endogenous_different": "switch: let each sector's green-investment share respond to relative costs",
    "lambda_is_optimal": "switch: use the optimal-portfolio lambda path",
    "stag_adjust": "stagnation adjustment applied to desired investment when population growth slows",
    "w_G_initial": "2021 risk weight on green loans",
    "w_G_2022": "risk weight on green loans from 2022",
    "w_C_S1_initial": "2021 risk weight on conventional loans, mining and utilities",
    "w_C_S2_initial": "2021 risk weight on conventional loans, manufacturing and construction",
    "w_C_S3_initial": "2021 risk weight on conventional loans, transport",
    "w_C_S4_initial": "2021 risk weight on conventional loans, other sectors",
    "w_C_S1_2022": "risk weight on conventional loans from 2022, mining and utilities",
    "w_C_S2_2022": "risk weight on conventional loans from 2022, manufacturing and construction",
    "w_C_S3_2022": "risk weight on conventional loans from 2022, transport",
    "w_C_S4_2022": "risk weight on conventional loans from 2022, other sectors",
}


def format_external_desc(name: str) -> str:
    """Table 6 (or Table 5) wording for an external; fall back to the symbol."""
    if name in TABLE6:
        return TABLE6[name]
    return table5_label(name) or name
